### PR TITLE
[CS2113T-W12-4]-Krazzen-B-DetectAnomaly(Bug Fixed)

### PR DESCRIPTION
**Pull request by Krazzen**
Bug fixed for function B-DetectAnomaly

### CODE REVIEW

**Comment by Krazzen** [comment]
Timings for deadline can be the same as it doesn't really affect the functionality? Maybe i can try doing a prompt for the user to confirm whether he or she wants the deadline even thought the deadline is the same.

**Comment by lionlim97** [comment]
oh good point. The prompt can be a value addition

**Comment by hwbjerry** [comment]
I create a alert box (JavaFx) for generally use to prompt the user. I implemented it in away it could be reused. So Don't have to create @Krazzen. Do you want me to push it so everyone can utilise it?

**Comment by Krazzen** [comment]
Can ah, i think it would be useful. @hwbjerry

**Pull request merged**
